import type { Sidebar } from '@/types/docs';

export const sidebar: Sidebar = [
  {
    sidebarLabel: 'Site development',
    devOnly: true,
    contents: [
      {
        slug: 'how-to/write-guides',
        sidebarLabel: 'Writing guides',
        devOnly: true,
      },
      {
        slug: 'reference/write-references',
        sidebarLabel: 'Writing references',
        devOnly: true,
      },
    ],
  },
  {
    sidebarLabel: 'Getting started',
    // May change when we revisit this section's boundary with Concepts (#1105)
    llmsDescription: 'Installation, project setup, and introductory guides.',
    contents: [
      { slug: 'how-to/installation' },
      {
        sidebarLabel: 'Migrate to Video.js 10',
        llmsDescription:
          'Guides for moving an existing player integration to Video.js v10, one per player you might be coming from.',
        defaultOpen: false,
        contents: [
          { slug: 'how-to/migrate-from-video-js-8', sidebarLabel: 'From Video.js 8' },
          { slug: 'how-to/migrate-from-mux-player', sidebarLabel: 'From Mux Player' },
          { slug: 'how-to/migrate-from-plyr', sidebarLabel: 'From Plyr' },
          { slug: 'how-to/migrate-from-media-chrome', sidebarLabel: 'From Media Chrome' },
        ],
      },
      { slug: 'concepts/why-videojs' },
      { slug: 'concepts/overview' },
      { slug: 'how-to/build-with-ai' },
      { slug: 'concepts/v10-roadmap', sidebarLabel: 'Roadmap' },
      { href: '/changelog', sidebarLabel: 'Changelog' },
      { slug: 'concepts/browser-support' },
      { slug: 'concepts/typescript' },
      { slug: 'concepts/bundlers' },
    ],
  },
  {
    sidebarLabel: 'Concepts',
    llmsDescription:
      'Understanding-oriented pages that explain how and why things work. Read these to build a mental model of the library.',
    contents: [
      { slug: 'concepts/features' },
      { slug: 'concepts/skins' },
      { slug: 'concepts/presets' },
      { slug: 'concepts/ui-components' },
      { slug: 'concepts/accessibility' },
      { slug: 'concepts/media-sources' },
      { slug: 'concepts/cast', sidebarLabel: 'Google Cast' },
      { slug: 'concepts/mux-data' },
      { slug: 'concepts/security' },
      { slug: 'concepts/i18n', sidebarLabel: 'Internationalization' },
    ],
  },
  {
    sidebarLabel: 'How to',
    llmsDescription:
      'Task-oriented guides with step-by-step instructions to achieve a specific outcome by applying one or more concepts. Each guide may assume you already understand the relevant concepts.',
    contents: [
      {
        sidebarLabel: 'Integrate with a framework',
        defaultOpen: false,
        contents: [
          { slug: 'how-to/use-videojs-with-vue', sidebarLabel: 'Vue and Nuxt', frameworks: ['html'] },
          { slug: 'how-to/use-videojs-with-svelte', sidebarLabel: 'Svelte and SvelteKit', frameworks: ['html'] },
        ],
      },
      { slug: 'how-to/customize-skins' },
      { slug: 'how-to/add-a-poster-placeholder' },
      { slug: 'how-to/add-a-background-video' },
      { slug: 'how-to/build-your-own-component' },
      { slug: 'how-to/self-host-the-player', frameworks: ['html'] },
      { href: 'https://github.com/videojs/v10/blob/main/CONTRIBUTING.md', sidebarLabel: 'Contribute to Video.js' },
      {
        sidebarLabel: 'Internationalization',
        defaultOpen: false,
        contents: [
          { slug: 'reference/translation-phrases', sidebarLabel: 'Translation keys' },
          { slug: 'how-to/i18n-register-locale', sidebarLabel: 'Register a locale' },
          { slug: 'how-to/i18n-override-translations', sidebarLabel: 'Override translations' },
          { slug: 'how-to/i18n-switch-locale', sidebarLabel: 'Switch locale' },
          { slug: 'how-to/i18n-ssr', sidebarLabel: 'SSR with locale' },
        ],
      },
    ],
  },
  {
    sidebarLabel: 'API Reference',
    llmsDescription:
      'Reference for every public export, grouped by what it is: UI components, media components, player features, and utilities.',
    contents: [
      {
        sidebarLabel: 'UI Components',
        defaultOpen: false,
        llmsDescription: 'API Reference for UI components for building media player interfaces.',
        contents: [
          { slug: 'reference/player-provider' },
          { slug: 'reference/player-container' },
          { slug: 'reference/i18n-provider', frameworks: ['react'] },
          // sorted alphabetically
          { slug: 'reference/airplay-button' },
          { slug: 'reference/alert-dialog' },
          { slug: 'reference/audio-track-radio-group' },
          { slug: 'reference/buffering-indicator' },
          { slug: 'reference/captions-button' },
          { slug: 'reference/captions-radio-group' },
          { slug: 'reference/cast-button' },
          { slug: 'reference/controls' },
          { slug: 'reference/error-dialog' },
          { slug: 'reference/fullscreen-button' },
          { slug: 'reference/gesture' },
          { slug: 'reference/google-cast' },
          { slug: 'reference/hotkey' },
          { slug: 'reference/menu' },
          { slug: 'reference/mute-button' },
          { slug: 'reference/mux-data' },
          { slug: 'reference/pip-button' },
          { slug: 'reference/play-button' },
          { slug: 'reference/playback-rate-button' },
          { slug: 'reference/playback-rate-radio-group' },
          { slug: 'reference/popover' },
          { slug: 'reference/poster' },
          { slug: 'reference/quality-radio-group' },
          { slug: 'reference/seek-button' },
          { slug: 'reference/seek-indicator' },
          { slug: 'reference/slider' },
          { slug: 'reference/status-announcer' },
          { slug: 'reference/status-indicator' },
          { slug: 'reference/thumbnail' },
          { slug: 'reference/time' },
          { slug: 'reference/time-slider' },
          { slug: 'reference/title' },
          { slug: 'reference/tooltip' },
          { slug: 'reference/volume-indicator' },
          { slug: 'reference/volume-popover' },
          { slug: 'reference/volume-slider' },
        ],
      },
      {
        sidebarLabel: 'Media Components',
        defaultOpen: false,
        llmsDescription: 'API Reference for media components that handle streaming protocols and media playback.',
        contents: [
          { slug: 'reference/audio' },
          { slug: 'reference/background-video' },
          { slug: 'reference/cloudflare-video' },
          { slug: 'reference/dash-video' },
          { slug: 'reference/hls-audio' },
          { slug: 'reference/hls-background-video' },
          { slug: 'reference/hls-video' },
          { slug: 'reference/hlsjs-video' },
          { slug: 'reference/mux-audio' },
          { slug: 'reference/mux-background-video' },
          { slug: 'reference/mux-video' },
          { slug: 'reference/native-hls-video' },
          { slug: 'reference/shaka-video' },
          { slug: 'reference/spotify-audio' },
          { slug: 'reference/tiktok-video' },
          { slug: 'reference/twitch-video' },
          { slug: 'reference/video' },
          { slug: 'reference/vimeo-video' },
          { slug: 'reference/youtube-video' },
        ],
      },
      {
        sidebarLabel: 'Player Features',
        defaultOpen: false,
        llmsDescription:
          'API reference for the feature modules passed to createPlayer, which provide player capabilities and state.',
        contents: [
          { slug: 'reference/create-selector' },
          { slug: 'reference/feature-buffer' },
          { slug: 'reference/feature-controls' },
          { slug: 'reference/feature-error' },
          { slug: 'reference/feature-fullscreen' },
          { slug: 'reference/feature-live' },
          { slug: 'reference/feature-metadata' },
          { slug: 'reference/feature-orientation-lock' },
          { slug: 'reference/feature-pip', sidebarLabel: 'Picture-in-picture' },
          { slug: 'reference/feature-playback' },
          { slug: 'reference/feature-playback-rate' },
          { slug: 'reference/feature-quality' },
          { slug: 'reference/feature-audio-track' },
          { slug: 'reference/feature-remote-playback' },
          { slug: 'reference/feature-source' },
          { slug: 'reference/feature-stream-type' },
          { slug: 'reference/feature-text-tracks' },
          { slug: 'reference/feature-time' },
          { slug: 'reference/feature-volume' },
        ],
      },
      {
        sidebarLabel: 'Utilities',
        defaultOpen: false,
        llmsDescription:
          'API reference for the hooks, utilities, controllers, and mixins used to integrate a player into an application.',
        // Flat by design: commonly used entries first, then the rest. Framework-specific
        // entries carry their own `frameworks`, so each framework sees one coherent list.
        contents: [
          { slug: 'reference/create-player', frameworks: ['react'] },
          { slug: 'reference/html-create-player', sidebarLabel: 'createPlayer', frameworks: ['html'] },
          { slug: 'reference/player-controller', frameworks: ['html'] },
          { slug: 'reference/use-player', frameworks: ['react'] },
          { slug: 'reference/use-media', frameworks: ['react'] },
          { slug: 'reference/use-container', frameworks: ['react'] },
          { slug: 'reference/use-store', frameworks: ['react'] },
          { slug: 'reference/create-i18n' },
          { slug: 'reference/use-translator', frameworks: ['react'] },
          { slug: 'reference/use-locale', frameworks: ['react'] },
          { slug: 'reference/media-i18n', sidebarLabel: 'media-i18n', frameworks: ['html'] },
          { slug: 'reference/media-text', sidebarLabel: 'media-text', frameworks: ['html'] },
          // Less commonly reached for
          { slug: 'reference/register-i18n', sidebarLabel: 'registerI18n' },
          { slug: 'reference/get-i18n-translations', sidebarLabel: 'getI18nTranslations' },
          { slug: 'reference/has-registered-locale', sidebarLabel: 'hasRegisteredLocale' },
          { slug: 'reference/on-i18n-registry-change', sidebarLabel: 'onI18nRegistryChange' },
          { slug: 'reference/create-translator', sidebarLabel: 'createTranslator' },
          { slug: 'reference/render-element', frameworks: ['react'] },
          { slug: 'reference/use-audio-track-options', frameworks: ['react'] },
          { slug: 'reference/use-button', frameworks: ['react'] },
          { slug: 'reference/use-captions-options', frameworks: ['react'] },
          { slug: 'reference/use-container-attach', frameworks: ['react'] },
          { slug: 'reference/use-media-attach', frameworks: ['react'] },
          { slug: 'reference/use-playback-rate-options', frameworks: ['react'] },
          { slug: 'reference/use-player-context', frameworks: ['react'] },
          { slug: 'reference/use-quality-options', frameworks: ['react'] },
          { slug: 'reference/use-selector', frameworks: ['react'] },
          { slug: 'reference/use-slider', frameworks: ['react'] },
          { slug: 'reference/use-snapshot', frameworks: ['react'] },
          { slug: 'reference/media-attach-mixin', frameworks: ['html'] },
          { slug: 'reference/player-context', frameworks: ['html'] },
          { slug: 'reference/provider-mixin', frameworks: ['html'] },
          { slug: 'reference/snapshot-controller', frameworks: ['html'] },
          { slug: 'reference/store-controller', frameworks: ['html'] },
        ],
      },
    ],
  },
];
